### ISSUE TITLE
Compiled on ESP32-Pico

### ISSUE THREAD

**Issue by DanielG86** [BjarneBitscrambler/SignalK-Orientation#2]
Hello Bjarne,

I've compiled your code now on an ESP32-Pico, an M5StackAtimLite module. They come in a nice form factor (incl physical button which you can use to store the calibration), and you can buy an ProtoKit to fit the sensor and a RS485 module to have a 12V input. Quite a nightmare before I got it running on PlatformIO though, but with some help on Slack, I have it operational now.

Next thing is to take a look at the calibration, which seems to be not so good, despite several actions to calibrate. I'll report back on the subject later

**Comment by DanielG86** [comment]
Made some mistakes in the Signal-K server, hence the adjusted issue title.

**Comment by BjarneBitscrambler** [comment]
Great to hear you got it working on some new hardware!  If you have any advice or summary of what you did to get it working, I'm happy to add that to the wiki.

For the calibration - I have found that getting it right can take some persistence, as there are a number of factors that can trip one up. Some of the important things to pay attention to include: keeping current-carrying wires away from the magnetometer sensor as much as possible, and fixing in place any wires that need to be nearby; performing the calibration 'twist and turn' motions in the area that the sensor will be used (so the magnetic environment doesn't change after mounting); and monitoring the quality-of-fit indicators while doing the calibration until you see satisfactory numbers.  

I have some additional hints in the wiki at https://github.com/BjarneBitscrambler/SignalK-Orientation/wiki   I've been adding to it as I discover things during my own testing. Feel free to reach out and let me know how it's going for you.  I do have a Slack account, but don't check there very often - the best way to reach me is here via Github, or email bhansen.victoria@gmail.com
