### ISSUE TITLE
new IMU?

### ISSUE THREAD

**Issue by wjquigs11** [BjarneBitscrambler/SignalK-Orientation#9]
The Adafruit 3463 has been discontinued, replaced by the 4517, which uses a different IMU and magnetometer. I'm assuming the code won't work on the 4517 but wanted to check. If not, any plans to update this repo? Or are there any modules still available that work with the existing code?

**Comment by BjarneBitscrambler** [comment]
I haven't experimented with the Adafruit 4517 (LSM6DSOX + LIS3MDL), but I see from its description that it uses I2C for communication. Therefore it should be possible to modify the existing firmware to work with the 4517.  This library (SignalK-Orientation) shouldn't need any modifications, but the underlying sensor fusion library (https://github.com/BjarneBitscrambler/OrientationSensorFusion-ESP) that handles the actual communication with the IMU will need changes.  

In that library's readme, under Customizing and Modifying (https://github.com/BjarneBitscrambler/OrientationSensorFusion-ESP#customizing-and-modifying), there are some suggestions as to what may need changing. Specifically, the ```driver_fxos8700.*``` and ```driver_fxas21002.*``` files will need modifications to talk to the new hardware. 
I'm not planning on doing those changes myself, as my existing units based on the earlier IMU are still performing fine, however you are welcome to give it a go.  Let me know how you progress, and feel free to ask me questions if something is unclear.

**Comment by wjquigs11** [comment]
Thanks. I will take a look at that code and see if I can handle it.
